name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ex1:
            - 'src/Exercice1/**'
          ex2:
            - 'src/Exercice2/**'
          ex3:
            - 'src/Exercice3/**'
          ex4:
            - 'src/Exercice4/**'

    - name: Exercice 1
      if: steps.filter.outputs.ex1 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex1
        args: --testdox

    - name: Exercice 2
      if: steps.filter.outputs.ex2 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex2
        args: --testdox

    - name: Exercice 3
      if: steps.filter.outputs.ex3 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex3
        args: --testdox

    - name: Exercice 4
      if: steps.filter.outputs.ex4 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex4
        args: --testdox
